name: Publish Gem

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: ruby
          package-name: fastlane-plugin-flutter_dart_version_manager
          version-file: 'lib\fastlane\plugin\flutter_dart_version_manager\version.rb'
